### ISSUE TITLE
flops control question

### ISSUE THREAD

**Issue by kunfei1** [Megvii-BaseDetection/DynamicRouting#19]
Hellow,
   I used default DynamicB config ,but set the small gate false, flops loss weight 0.3 and mu 0.2. The mean real flops of result is 3.05 flops, and Raw-config's is 75. The result is not 0.2*75=15 which is I want. I have some confusion for it and could you share some experience about how to use the scale to control the flops.

Looking forward for your reply!

**Comment by yanwei-li** [comment]
It's a good question. Actually, the \mu in the config controls the _expected_ flops rather than the _real_ flops in the optimization process. The bigger loss weight and the smaller \mu, which means the heavier constraint, would bring more flops drop (of course may have performance decrease). 

And I'm wondering if the _"mean real flops of result"_ has been reduced to _"3.05 flops"_ or _"30.5 flops"_ ? I mean it's strange to reduce the 75 flops to 3.05 flops in the given config.

**Comment by kunfei1** [comment]
您好，我又检查了一下结果 ，发现主要原因是由于基础flops不同，Dynamic_B的基础real_flops是42，所以有42*0.1-> 3.05，Seg.Layer16的基础real_flops显示是115，得到的mean_flops为75。但是我对比了一下两个config，发现除了smallgate其他选项都一样，我之前已经Dynamic_B的smallgate设为false了，想麻烦您再帮看一下为什么这两个设置得到的基础的real_flops差距比较大呀

**Comment by yanwei-li** [comment]
Hi! Has the `FIX_SIZE_FOR_FLOPS` bee set to `[768,768]` and `[1024,2048]` for training and evaluation (as is noted in `README`), respectively? I guess the `FIX_SIZE_FOR_FLOPS` could be the reason to this phenomenon.

**Comment by kunfei1** [comment]
我检查了一下，这两个参数在默认设置里面就是一样的
