### ISSUE TITLE
About Network-Fix

### ISSUE THREAD

**Issue by ceasorcai** [Megvii-BaseDetection/DynamicRouting#32]
Hi, thanks for sharing the code. How to obtain the Network-Fix?  I set GATE_ON=False in config.py and trained 186k iters on cityscapes, when I evaluated on the Cityscapes val set, the mIoU is 77.2757, the performance is better than dynamic-raw.  I don't kown why,  is there anything wrong when I obtain the Network-Fix, can you help me?

**Comment by yanwei-li** [comment]
Hi, your setting to obtain Network-Fix is right. Is ImageNet pretrained model used in your experiments? If it is used, the performance of Dynamic-Raw should be 78.6. If it is not used, it could be an outlier because of the lack of initialization. And the performance could vary with different experiments. More runs are recommended for this phenomenon.

**Comment by ceasorcai** [comment]
Thanks, I didn't use ImageNet pretrained model.
